### ISSUE TITLE
Global statistics over hash functions like MD5, SHA1

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#10]
Hello,

I want to visualize the distribution of used Hash-Functions like MD5 or SHA. 

The JSON Object should be a kind of following: 

``` javascript
[
  {
    "Hashfunction": MD5,
    "amount" : 30234,
  },
  {
    "Hashfunction": "Sha256",
     "amount" : 465345
  }
....
]
```

The problem here is, that a Server may support several hash functions, so we will exceed the 100%. 

Thank you for your engagement.

**Comment by zirkler** [comment]
Hi Lukas,

you can now access the requested data at this enpoint: http://tls.thejetlag.de:1337/api/v0/mac/distribution
