### ISSUE TITLE
Missing Key in DH JSON

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#12]
I found a mistake in the JSON object for November of http://tls.thejetlag.de:1337/api/v0/pfs/distribution
The "kxStrength" key is missing here and that is bad because the next values are not in the right place in my Graph. 

``` javascript
{
    "_id": "565d24465893d3cf7015e42f",
    "kx": "DH",
    "count": ​13706

},
```

**Comment by Lukas1Komarek** [comment]
There is also an undefined entry for 'ECDH' in november. The december looks okay. 

``` javascript
{

    "_id": "565d24465893d3cf7015e42e",
    "kx": "ECDH",
    "count": ​12084

},
```

**Comment by zirkler** [comment]
This is also attributed to an outdated openssl version / scanner problem.

**Comment by zirkler** [comment]
Ignore these objects for a while, till we have the new scanner with its own openssl compliate.
