### ISSUE TITLE
Query: RSA Key Sizes

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#16]
We need a JSON that gives us information about the RSA Keysizes (the pub key)

Should look something like this:

``` javascript
[ 
 { "Keysize": 2048, "amount": 231243 }
 {...}
]


```

:key:  :computer:

**Comment by zirkler** [comment]
Hi @MdaaaaO,
assigned you, because I think this is a good "getting started" query.

**Comment by MdaaaaO** [comment]
OK. I'm on it!

**Comment by MdaaaaO** [comment]
done... access: .../api/v0/keysize/keysize

**Comment by zirkler** [comment]
Okay this still needs a little bit of work:
- keysizes per tld
- keysizes per month
- codestyle

Please use an own branch for this feature. :+1:

**Comment by MdaaaaO** [comment]
http://localhost:1337/api/v0/keysize/overview

![overview](https://cloud.githubusercontent.com/assets/12131490/11908321/5a14a902-a5db-11e5-98f3-5beef2ce2a7d.PNG)

http://localhost:1337/api/v0/keysize/tld

![tld](https://cloud.githubusercontent.com/assets/12131490/11908324/6022982c-a5db-11e5-9a17-2a186cc1793c.PNG)

need live tests now
