### ISSUE TITLE
All 'High-Level' Graphs (pfs, dhe, ecdh,logjam...) should have TLD specific information  

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#17]
Seedorf wished to have the Information we have in the 'high level' (the summarized data, like pfs,dhe, ecdhe, logjam,..)  also for each TLD Domain. 
So my question is: Do you extend the existing JSONs or should we use Nicos' pattern matching Filter?

**Comment by ghost** [comment]
The filter function itself relies on an endpoint capable of returning data according to a certain top level domain (which the current endpoint that the database team provided us with does perfectly well). In other words: As soon as the filter comes into play, the data is already filtered according to a top level domain, the filter then applies further search criteria such as the protocol and the cipher string. Hence, my suggestion is to extend the JSON objects and make the TLD-filtered data available by providing an endpoint comparable to what was implemented for the filter function.

**Comment by Lukas1Komarek** [comment]
Chris mentioned, that the problem of the summary data is that you have only absolute numbers. You can't definitely say how many of e.g. .int Domain use PFS.

**Comment by ghost** [comment]
Yes, we can (quoting Obama not intended), provided that we display the result data according to their protocol in order to prevent hosts occuring in multiple "count" data fields from being summed up. Indeed, if we allowed summing up those counts (which is, by the way, the current state, but not for much longer), the "total hosts" number would be incorrect as an upper 100 % limit.

**Comment by zirkler** [comment]
What is going on here? Needs further discussion. Please be more precise when creating API requirement issues.

**Comment by zirkler** [comment]
TheJetlag:
Provide tld specific output for these endpoints:
- [x] /pfs/overview
- [x] /pfs/distribution
- [x] /mac/distribution
- [x] /ciphers/summary

**Comment by zirkler** [comment]
Hi together,

all high level endpoints now support tld specific filtering.
See the wiki for further information and example requests.
