### ISSUE TITLE
Provide fake data in order to simulate at least four months of scanning

### ISSUE THREAD

**Issue by ghost** [hft-swp2-ws1516/db-api#19]
In order to test the filter function and verify that it is working correctly, it would be extremely helpful to have access to some fake data that simulates at least four months of scanning progress. In more precise words: Copy-paste entries of different top-level domains with approximately the same number for their total hosts in one document and then change them so that they have a common top-level domain (".test" for example in order not to confuse them with "real" entries) as well as ongoing month and year information (2015_11, 2015_12, 2016_1, ...). The data can, of course, be static - there is no need to keep them up-to-date in whatever dynamic kind of way.

**Comment by zirkler** [comment]
available here: http://hotcat.de:1337/api/v0/ciphers/summary?tld=test
