### ISSUE TITLE
Mac Distribution: Where did the november go? / null cipher

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#21]
1. http://h2511680.stratoserver.net:1337/api/v0/mac/distribution 
   The data for November suddenly disappeared this morning.
2. There is a MAC with the name null:

``` javascript
{

    "_id": "566e670ebb08f5c5338d6764",
    "mac": null,
    "count": ​102041

}

```

**Comment by zirkler** [comment]
November is back. Thanks for reporting this issue.
