### ISSUE TITLE
Query: Distribution of authentification methods on TLS server

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#22]
Another interesting thing could be the distribution of supported authentification methods.  

``` javascript

var Authentication_Methods_Frequency = [
    {"RSA": 40},
    { "DH_DSS": 123},
    { "ECDSA": 356},
    ...
    totalNumberOfHosts: xxx,
];

```

Example: The following question should be answered: 
How many Hosts support RSA as authentification algorithm. The absolute number can be already filtered out by the cipher summary.

[ ] Also results per month
[ ] Results separated by tld

Important note: A Host can supply more than only one Key-Exchange-Method. So the sum of the counts can exceed the total number of hosts

**Comment by zirkler** [comment]
Done.
i.e.: 
https://hotcat.de:1337/api/v0/auth/overview?tld=com
https://hotcat.de:1337/api/v0/auth/overview
