### ISSUE TITLE
Query: Distribution of Key-Exchange Methods

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#23]
Similar to #22.

``` javascript
var Keyexchange_Methods_Distribution = [
    {"RSA": 473,688 },
    { "DHE": 283,647},
    { "ECDHE": 85,070},
    ...
    totalNumberOfHosts: xxx,
];
```

[ ] Also results per month
[ ] Results separated by tld

Important note: A Host can supply more than only one Key-Exchange-Method. So the sum of the counts can exceed the total number of hosts

**Comment by zirkler** [comment]
Done.
https://hotcat.de:1337/api/v0/kx/overview?tld=com
https://hotcat.de:1337/api/v0/kx/overview
