### ISSUE TITLE
Query: Distribution of Bulk Encryption Methods

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#24]
Similar to #22 and #23.

``` javascript
var BulkEnc_Methods_Distribution = [
    {"AES128": 323423 },
    { "AESGCM(256)": 2345344},
    { "AES(256": 85.3342},
    ...
    totalNumberOfHosts: xxx,
];

```

[ ] Also results per month
[ ] Results separated by TLD

Important note: A Host can supply more than only one Bulk-Encryption-Methods. So the sum of the counts can exceed the total number of hosts

**Comment by zirkler** [comment]
Done.
https://hotcat.de:1337/api/v0/enc/overview
https://hotcat.de:1337/api/v0/enc/overview?tld=com
