### ISSUE TITLE
Missing Total Number of Hosts in DHE, MAC 

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#25]
For percentual line graphs we need the Total Number of Hosts for DHE/ECDHE and MAC distribution.

**Comment by zirkler** [comment]
Hi,

we now have an dedicated endpoint for the host counting:
count all hosts: http://hotcat.de:1337/api/v0/hostcount 
for tld specific counting: http://hotcat.de:1337/api/v0/hostcount?tld=com
