### ISSUE TITLE
Different hostcount in summary and hostcount-endpoint

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#28]
This is confusing me and an explanation would be nice.

```
http://h2511680.stratoserver.net:1337/api/v0/ciphers/summary?tld=de
```

Total hostcount for November: ​20483

```
http://hotcat.de:1337/api/v0/hostcount?tld=de
```

Total hostcount for November: ​14935

**Comment by zirkler** [comment]
Please rely on the host-count endpoint. The totalHosts-fields in the specific endpoints will be removed in the future.
