### ISSUE TITLE
Filter: Prevent last scanned month from being shown in filter endpoint

### ISSUE THREAD

**Issue by ghost** [hft-swp2-ws1516/db-api#29]
Until the current month has not reached its end, its scanning results are not complete. Thus, displaying them in a graph on the website is misleading to the user. The very beginning of a month is particularly problematic as the results are only an empty pair of edgy brackets. After all, it is desirable that the current month being scanned does not appear in the endpoint that the website's filter function uses.

**Comment by zirkler** [comment]
Hi Nico,
done by b50dc3eba5e2f1bb139f6dc034f677261dfb2b41.
