### ISSUE TITLE
Query: How many Servers supports PFS? 

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#4]
Need a Json Object, that tells me how many Server Supports the ECDHE or DHE Key-Exchange Method. It doest matter if the value is % or just the count.  
- [] available and prefered
- [] only prefered

``` javascript
pfs = [
    {"PFS enabled": 80},
    { "PFS Disabled": 20},
];
```

_Thanks!_

**Comment by zirkler** [comment]
closed by a665d9b10d9a706f0e40b75852d64d16b1f1b0f1
Have fun: http://tls.thejetlag.de:1337/api/v0/pfs/overview
