### ISSUE TITLE
Query: Diffie Hellman Parameter size support for DHE

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#5]
We need a JSON Object that shows the contribution of DHE Parameters keygroups.

For visualisation it's important to know how many TLS Servers who enabled dhe were scanned. Because it is possible that a Server may support different Parameter sizes.

``` javascript
    var testdaten = {
       "dhe":[
       {
        "keygroup": "256",
        "counts": 312,
    },
    {
        "keygroup": "512",
        "counts": 31232,
    },
    {
      "keygroup": "768",
      "counts": 6534,       },
      {
          "keygroup": "1024",
          "counts": 256434,
      },
      {
          "keygroup": "2048",
          "counts": 65100,
      },


      ]

  };

```

**Comment by zirkler** [comment]
closed by a665d9b10d9a706f0e40b75852d64d16b1f1b0f1
Have fun: http://tls.thejetlag.de:1337/api/v0/pfs/distribution
