### ISSUE TITLE
Function: Implementing filter functionality

### ISSUE THREAD

**Issue by ghost** [hft-swp2-ws1516/db-api#6]
Our website provides the user with the possibility to construct his own cipher string which should then be used to search the scanned data and give the user a feedback about how many of the scanned URLs in total support the cipher properties given by displaying the results in a chart. A method implementing this functionality should take the following arguments:

1.) A top level domain, if null is given look for all domains.
2.) The SSL/TLS protocol, again if null is given include all protocols.
3.) The cipher string that the user has constructed using the web interface.
4.) A From date and a To date, each consisting of the month and the year, thus defining a time span.

The method should then return the following information: 

1.) The total number of URLs available for the user's selection regarding the top-level domain.
2.) The number of URLs matching the properties provided by the user (protocol and cipher string) for each month lying in the time span the user has selected, including the start and end month (could for example be a key-value pair for every month using the month/year combination as the key and the number of matching URLs as the value).

**Comment by zirkler** [comment]
Hi Niko,

as we have already discussed, the `/ciphers/summary` endpoint now supports the top-level domain as parameter, like `/ciphers/summary?tld=ru`.

The result now also contains a `totalHosts` attribute, which specifies how many hosts where scanned in the specific month.

Based on this information you can iterate over the `summary` array and grab all the cipher suites which matches your specified filters.
