### ISSUE TITLE
Logjam Attack

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#8]
Hey guyz. We need some JSON shit for following issue:
"The logjam attack affects any server that supports DHE_EXPORT ciphers. It affects all modern web browsers. 8.4% of the Top 1 Million domains were initially vulnerable". (https://weakdh.org/)

So, Ciphers that include "EXP" or "Export" are vulnerable.

**Comment by zirkler** [comment]
Hi Lukas,

the `/ciphers/summary` endpoint returns all the different ciphers suites, with a count attribute (how many hosts support that cipher suite), grouped by month. This also includes EXP cipher suites. I think you can aggregate the information from this endpoint very easy, just look for the EXP cipher suites where the status is set to "accepted".

**Comment by zirkler** [comment]
The `exp/overview` route is solving this issue now.
