### ISSUE TITLE
Frequency of Ciphersuites + History (line diagramm) 

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/db-api#9]
Hey db experts, we need more JSON shit:

Don't know if there is a redundancy with Nico's Filter Functionality.

A Graph that supplies ordered information about the frequency of a all Ciphersuites.

``` javascript
 var most_used_ciphersuites = [
    {"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256": 42},
    { "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384": 1337},
    {...}
];
```

History

We need a history of how the frequency of a cipher suites changed in a given timespan. This will be displayed in a line diagram.

**Comment by zirkler** [comment]
Hi Lukas,

the `/ciphers/summary` endpoint returns all the different ciphers suites, with a count attribute (how many hosts support that cipher suite), grouped by month. I'm pretty sure this is fulfilling your requirements.
